---
name: Spyglass-Sniper
main: nopenotdark\spyglass_sniper\Snipers
description: A plugin that adds a sniper to the game!
version: 2.0.2-ALPHA
authors:
  - SantanasWRLD
  - NopeNotDark
api: 5.0.0
...
