---
name: Spyglass-Sniper
main: nopenotdark\spyglass_sniper\Snipers
description: A plugin that adds a sniper to the game!
version: 1.0.8-SNAPSHOT
authors:
  - SantanasWRLD
  - NopeNotDark
api: 5.0.0
...
